spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db
spring.datasource.username=root
spring.datasource.password=hgYiM7KeG6T*6UE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=7yA9mN2KxL5QpR8vW1ZcD4EfGhJkLmNpQrStUvWxYz123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect