spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db
spring.datasource.username=root
spring.datasource.password=hgYiM7KeG6T*6UE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true